language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: R+Ot7Hv1t/jwFCwQkI86dQl2FPnlqaiyjogGZfFTWqs+HHPXp4k2W2gSasBXPKpg2oysouXrcItQ7D633YkGnc3zh+y0vAQ58t8GJr6juxAYwTICAOse+6D13LpsCE8SEAiXU+eVzw11XF27T2HSjuq5wwGWqluqp9T3/jFUFnf+uslYCGI/dMyRel4F58DNIRc+IvNLZ05yayL2zNg9ePft7sD4wQMeVNuSRLehY95aBbxKsKb9dYkRcUn/58sYIxKcxeDLZE3fdYyR/S3AuKnCuHt0vtKoJcgZb3YF96qIm7c73OCJVque7mNPXp+zRxoHL7mDBrNfch4kY01M0Vj6eFy/MW0q0VKxeXKwtmjThPGwmV2N9tcbVIfqGlylMXz2tE9V5x0rj1HdFmHj2hilTT8BE9yotzuAkDxJFkoyutkG52FiDyo6RkJGzAfHr3ZNE7W9fNqTIDhQLQpgPEceqgQepEEXdJMpyb5od2VMOU1qQ0BA6y9ATOTCEQc3qOmmZafwQVg2j6b2QaGwMSSQR8AXYusj7UCjpArkAsdrnIYcOzZo/hxZapXApl7KlADjUvsAMdCGNeWenQAdTwjAxTftgoPdiEg7Xlw8ds19BQVfI+QGrDr90J2SVjSvh8xiM1yzyKePUvbHn9OOXFsC8elw4rIA/gLLaoTDADQ=
